MOB-1521 No internet screen refresh
ecosia/ios-browser pull request #424
Opened 2023-03-20 18:42 UTC by d4r1091

[MOB-1521](https://ecosia.atlassian.net/browse/MOB-1521)

This ticket has been instrumental in understanding a bit more about how the codebase collaborates with internal definitions of HTML/CSS.

This PR updates the copies and fixes the image on the _"No Internet screen"_.
This page is indeed a static web page.
As part of the copy update work, I've also improved the methodology for loading the error image within the web page.
We were grabbing a `png` without the standard 1x/2x/3x resolutions that Apple provided.
So, once I fixed the retrieval, I realized that the image was blurred.
Fix applied by importing the `pdf` of the same image as part of our asset and loading the data via `UIImage.pngData()`

Note: in Figma, the padding looks different. I didn't want to start modifying the `HTML/CSS` made by Firefox as I didn't think it would add much value to the work.

Next step would be to understand in practice how the localization process works.

The result is in the screenshot attached.

![IMG_D6C86E2A5EF1-1](https://user-images.githubusercontent.com/3584008/226435815-2f3cc7d7-d391-4319-919a-e26982368c0c.jpeg)

2023-03-21 09:10 UTC, ecotopian requested changes
Great work!! This was a tricky quite tangled task, and without any pointer from my side you find the right spots in the codebase. That is impressive! 🚀 👏 

Still before I can approve you need to either provide our own l10n for the added strings or find them in MZ's code to continue. You find docs about how to use TF here:
https://github.com/ecosia/ios-browser#translations

I am happy to assist you there.

2023-03-21 09:10 UTC, ecotopian commented on Client/Ecosia/Extensions/ErrorPageHandler+Ecosia.swift
> +/// These strings modify the default title, message and button text
📖 great habit to add explanatory documentation for new classes 👍

2023-03-21 09:10 UTC, ecotopian commented on Client/Frontend/InternalSchemeHandler/InternalSchemeHandler.swift
> +                      let data = UIImage(named: "noInternet")?.pngData() {
great fix 💪

2023-03-21 09:10 UTC, ecotopian commented on Client/Ecosia/L10N/String.swift
> +        case noConnectionNSURLErrorTitle = "No connection"
I see that you introduced those three string. I wonder if they are in some form existing in FF's l10n already. If so we don't need to provide our own translation and use the given ones, which in this case are missing. But I am happy to explain to you how to get those 🚀

2023-03-23 08:56 UTC, d4r1091 commented
Checked the translations this morning @ecotopian. All the required languages have been translated.
You can check in the last commit 👍

2023-03-23 10:01 UTC, merged